---
- name: Create a new user
  hosts: all
  gather_facts: False
  connection: local
  tasks:
    - name: Creating new user...
      ios_user:
         name: service_now2
         configured_password: autonetops
         password_type: secret
         privilege: 15
         state: present